plugins {
  id 'com.android.library'
  id 'app.cash.paparazzi'
}

android {
  namespace = 'app.cash.paparazzi.plugin.test'
  compileSdk = libs.versions.compileSdk.get() as int
  defaultConfig {
    minSdk = libs.versions.minSdk.get() as int
  }
  compileOptions {
    sourceCompatibility = libs.versions.javaTarget.get()
    targetCompatibility = libs.versions.javaTarget.get()
  }
}

paparazzi {
  layoutlibVersion = "16.2.4"
}

dependencies {
  testImplementation libs.truth
}

