plugins {
  id 'com.android.library'
  id 'app.cash.paparazzi'
}

android {
  namespace = 'app.cash.paparazzi.plugin.test'
  compileSdk = libs.versions.compileSdk.get() as int
  defaultConfig {
    minSdk = libs.versions.minSdk.get() as int
  }
  compileOptions {
    sourceCompatibility = libs.versions.javaTarget.get()
    targetCompatibility = libs.versions.javaTarget.get()
  }
}

dependencies {
  testImplementation libs.junit.jupiter
  // Gradle requires the launcher on the runtime classpath for JUnit Platform; the plugin only
  // adds it itself in native mode.
  testRuntimeOnly libs.junit.platform.launcher
}

tasks.withType(Test).configureEach {
  useJUnitPlatform()
}
