name: publish-layoutlib

on:
  workflow_dispatch:

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:

  publish:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'publish-layoutlib')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      # VERSION_NAME needs to be a non-snapshot version to ensure we can publish signed artifacts
      - name: Publish Artifacts
        run: ./gradlew publishMavenNativeLibraryPublicationToMavenCentralRepository -PVERSION_NAME=1.0.0
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}
